### ISSUE TITLE
XP Teleport Bug When Change Dimension

### ISSUE THREAD

**Issue by XingYanTW** [BlossomMods/BlossomLib#11]
XP will set to zero to client when change dimension via /home or /warp
It's need to rejoin or get xp to restore the bug.

**Comment by CodedSakura** [comment]
hi, sorry for the delay, but just realized that i need to confirm that you experienced this bug with the `enableMC124177Fix` option set to `true`, right? or did you have it set to `false` for some reason?

**Comment by XingYanTW** [comment]
Yes it's set to true

**Comment by CodedSakura** [comment]
what versions of minecraft, blossomlib and blossomhomes/warps are you using?

**Comment by XingYanTW** [comment]
Minecraft 1.20
blossom-lib 2.5.1+1.20
blossom-tpa 2.1.1+1.20
blossom-warps 2.0.4+1.20

**Comment by CodedSakura** [comment]
ugh, keep forgetting to mention issues in commits, but should be fixed in 2.5.1-fix.1 (67dbbff27d09eaafaebdc63da999445ccda519a2)
