### ISSUE TITLE
Wrong label in modrinth

### ISSUE THREAD

**Issue by IfgiU** [BlossomMods/BlossomLib#13]
Hi!
[This](https://modrinth.com/mod/blossomlib/version/2.5.1+1.19.4) version of the mod says that it's compatible with fabric 1.19.3,
even though the server throws an error:
```
Unmet dependency listing:
	 - Mod 'BlossomLib' (blossom-lib) 2.5.1+1.19.4 requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
```

Now, either the mod doesn't function correctly, or the file is misslabeled.

**Comment by CodedSakura** [comment]
the jar is labeled as 1.19.4 only, but that can easily be overwritten with a [dependency override](https://fabricmc.net/wiki/tutorial:dependency_overrides). imo 1.19.3 is a very niche version and i don't feel like re-publishing it with correct details (until the next blossomlib update at least, as i'll continue 1.19-1.19.4 support for a while, and will fix in next 1.19.3/4 release)
