### ISSUE TITLE
BlossomLib causes the player to be unable to join the server

### ISSUE THREAD

**Issue by BackWheel** [BlossomMods/BlossomLib#2]
When I add the BlossomLib to the server mod file and start the server, I can't join the server. The game prompts me for "Invaild player data"
![image](https://user-images.githubusercontent.com/41251296/179682333-db5f116e-90a0-4f09-8143-d1757377950c.png)

Here are the server logs:
[latest.log](https://github.com/BlossomMods/BlossomLib/files/9138174/latest.log)

Here are the BlossomMod logs:
[BlossomMods.log](https://github.com/BlossomMods/BlossomLib/files/9138183/BlossomMods.log)

**Comment by BackWheel** [comment]
Supplementary information
Version : 1.19
Fabric Loader version : 0.14.8
BlossomLib version: 2.3.0

Here is a list of mods for the server：
![image](https://user-images.githubusercontent.com/41251296/179683213-20a54a46-c22f-4d95-b10c-f23d4c0d0e6b.png)
![image](https://user-images.githubusercontent.com/41251296/179683255-6f800371-adc1-4a86-b0f4-d96addda14f6.png)

It is known that after I delete BlossomLib, the server will let me in.

**Comment by CodedSakura** [comment]
could you try setting `enableMC124177Fix` to `false` in the BlossomLib config?

**Comment by BackWheel** [comment]
Well, the problem was fixed when I changed the setting. But I wonder if this change will have a negative impact on the game？

**Comment by CodedSakura** [comment]
it's likely that one of the performance mods you have already fixes this issue, but i might add a safeguard to my fix anyway

**Comment by BackWheel** [comment]
Ok I understand
