### ISSUE TITLE
how do i download

### ISSUE THREAD

**Issue by MalacoX** [BlossomMods/BlossomLib#9]
sorry im too stupid to know how to download mods off of github, is it the zip folder of blossomlib that i have to unzip or is it an actual jar file

**Comment by iMystxc-dev** [comment]
![image](https://github.com/BlossomMods/BlossomLib/assets/85364772/09dad0c1-15ab-4988-b853-99d0d01b8641)
u can find the releases tab on the right hand side, you'll find the jar file there

**Comment by MalacoX** [comment]
thanks man!
